In [3]:
import pandas as pd

In [5]:
# load excel file

df = pd.read_excel('data.xlsx')

In [7]:
df.head()

,Timestamp,What is your age?,What is your gender?,What is your class?,What foods do you love to eat for breakfast? Select all that apply.,What foods do you love to eat for lunch? Select all that apply.,What foods do you love to eat for dinner? Select all that apply.,Are there any foods you dislike? Select all that apply.,Do you have any food allergies? Select all that apply.,Thank you for completing the survey. Do you have any additional suggestions or comments?
0,2025-02-06 08:35:06.187,15-18,Female,100 level,Moi-Moi,Jollof Rice,Indomie and Egg,Eba,Peanuts Groundnut),NaN
1,2025-02-06 08:39:28.901,19-22,Female,400 level,"Yam, Jollof Rice, Bread, White Rice, Egg, Plai...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Beans, Jollof Rice, Fried Rice, Bread, White R...","Fish, Soda drink",Nil,Nil
2,2025-02-06 08:40:47.541,15-18,Female,100 level,"White Rice, Spaghetti, Plaintain, Youghurt, Ch...","Fish, Amala",Indomie and Egg,"Beans, Eba",Soy,No
3,2025-02-06 08:41:03.113,19-22,Female,400 level,"Jollof Rice, Fried Rice, Bread, White Rice, Sp...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Shawarma and chips, Jollof Rice, Fried Rice, B...",Fish,Diary and milk,NaN
4,2025-02-06 08:41:03.734,15-18,Female,100 level,Cereal,"Bread,",Rice,"Beans, Amala",At all,No

In [9]:
# Rename Columns for ease
df.columns = ['time','age','gender','class','breakfast', 'lunch', 'dinner', 'dislikes','allergies','comments']

In [11]:
df.head()

,time,age,gender,class,breakfast,lunch,dinner,dislikes,allergies,comments
0,2025-02-06 08:35:06.187,15-18,Female,100 level,Moi-Moi,Jollof Rice,Indomie and Egg,Eba,Peanuts Groundnut),NaN
1,2025-02-06 08:39:28.901,19-22,Female,400 level,"Yam, Jollof Rice, Bread, White Rice, Egg, Plai...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Beans, Jollof Rice, Fried Rice, Bread, White R...","Fish, Soda drink",Nil,Nil
2,2025-02-06 08:40:47.541,15-18,Female,100 level,"White Rice, Spaghetti, Plaintain, Youghurt, Ch...","Fish, Amala",Indomie and Egg,"Beans, Eba",Soy,No
3,2025-02-06 08:41:03.113,19-22,Female,400 level,"Jollof Rice, Fried Rice, Bread, White Rice, Sp...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Shawarma and chips, Jollof Rice, Fried Rice, B...",Fish,Diary and milk,NaN
4,2025-02-06 08:41:03.734,15-18,Female,100 level,Cereal,"Bread,",Rice,"Beans, Amala",At all,No

In [17]:
# Create unified preference list
def get_pref_vector(row):
    foods = []
    for col in ['breakfast','lunch','dinner']:
        if pd.notnull(row[col]):
            foods +=[f.strip().lower() for f in row[col].split(',')]

    return foods

In [47]:
df['preferences'] = df.apply(get_pref_vector,axis=1)
df['preferences'].head()

0              [moi-moi, jollof rice, indomie and egg]
1    [yam, jollof rice, bread, white rice, egg, pla...
2    [white rice, spaghetti, plaintain, youghurt, c...
3    [jollof rice, fried rice, bread, white rice, s...
4                              [cereal, bread, , rice]
Name: preferences, dtype: object

In [69]:
df.head()

,time,age,gender,class,breakfast,lunch,dinner,dislikes,allergies,comments,...,soda drink,salad & fruits,coochie,bread and egg,plaintain,tea,jollof rice,bread and tea.. i guess,toast bread,cerael
0,2025-02-06 08:35:06.187,15-18,Female,100 level,Moi-Moi,Jollof Rice,Indomie and Egg,Eba,Peanuts Groundnut),NaN,...,0,0,0,0,0,0,1,0,0,0
1,2025-02-06 08:39:28.901,19-22,Female,400 level,"Yam, Jollof Rice, Bread, White Rice, Egg, Plai...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Beans, Jollof Rice, Fried Rice, Bread, White R...","Fish, Soda drink",Nil,Nil,...,0,0,0,0,1,0,1,0,0,0
2,2025-02-06 08:40:47.541,15-18,Female,100 level,"White Rice, Spaghetti, Plaintain, Youghurt, Ch...","Fish, Amala",Indomie and Egg,"Beans, Eba",Soy,No,...,0,0,0,0,1,0,0,0,0,0
3,2025-02-06 08:41:03.113,19-22,Female,400 level,"Jollof Rice, Fried Rice, Bread, White Rice, Sp...","Fried Rice, Yam, Bread, White Rice, Beans, Egg...","Shawarma and chips, Jollof Rice, Fried Rice, B...",Fish,Diary and milk,NaN,...,0,0,0,0,1,0,1,0,0,0
4,2025-02-06 08:41:03.734,15-18,Female,100 level,Cereal,"Bread,",Rice,"Beans, Amala",At all,No,...,0,0,0,0,0,0,0,0,0,0

In [73]:
#len(df.columns)
df.columns

Index(['time', 'age', 'gender', 'class', 'breakfast', 'lunch', 'dinner',
       'dislikes', 'allergies', 'comments', 'preferences', '', 'egg',
       'fried rice', 'moi-moi', 'indomie and egg', 'starch', 'eba', 'rice',
       'fufu', 'semo', 'bread and omlette with some tea', 'alfredo pasta',
       'meat', 'shawarma and chips', 'egusi soup', 'yam',
       'starch and other swallows', 'coffee', 'eba and soup', 'cereal',
       'fried yam/potatoes and vegetables', 'pizza 🍕', 'amala', 'potato',
       'i dont eat dinner', 'spaghetti', 'chicken',
       'pizza and ice cream (sweet cream', 'smoothie', 'fruit salad',
       'intercontinental dishes', 'fish', 'white rice', 'beans', 'pounded yam',
       'bread', 'anything my money can get me', 'youghurt', 'soda drink',
       'salad & fruits', 'coochie', 'bread and egg', 'plaintain', 'tea',
       'jollof rice', 'bread and tea.. i guess', 'toast bread', 'cerael'],
      dtype='object')

In [49]:
# Get all unique food items
all_foods = set(food for sublist in df['preferences'] for food in sublist)
all_foods

{'',
 'alfredo pasta',
 'amala',
 'anything my money can get me',
 'beans',
 'bread',
 'bread and egg',
 'bread and omlette with some tea',
 'bread and tea.. i guess',
 'cerael',
 'cereal',
 'chicken',
 'coffee',
 'coochie',
 'eba',
 'eba and soup',
 'egg',
 'egusi soup',
 'fish',
 'fried rice',
 'fried yam/potatoes and vegetables',
 'fruit salad',
 'fufu',
 'i dont eat dinner',
 'indomie and egg',
 'intercontinental dishes',
 'jollof rice',
 'meat',
 'moi-moi',
 'pizza and ice cream (sweet cream',
 'pizza 🍕',
 'plaintain',
 'potato',
 'pounded yam',
 'rice',
 'salad & fruits',
 'semo',
 'shawarma and chips',
 'smoothie',
 'soda drink',
 'spaghetti',
 'starch',
 'starch and other swallows',
 'tea',
 'toast bread',
 'white rice',
 'yam',
 'youghurt'}

In [51]:
# create binary columns for each food
for food in all_foods:
    df[food] = df['preferences'].apply(lambda x:1 if food in x else 0)

# user0food matrix
user_food_matrix = df[list(all_foods)]
user_food_matrix

,,egg,fried rice,moi-moi,indomie and egg,starch,eba,rice,fufu,semo,...,soda drink,salad & fruits,coochie,bread and egg,plaintain,tea,jollof rice,bread and tea.. i guess,toast bread,cerael
0,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,1,1,0,1,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,1,1,0,1,0,1,0,0,1,...,0,0,0,0,1,0,1,0,0,0
4,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,0,1,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
145,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
146,0,1,1,1,1,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
147,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
148,0,1,1,1,0,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

# compute Cosine Similarity between users
user_sim = cosine_similarity(user_food_matrix)
user_sim

array([[1.        , 0.28005602, 0.20412415, ..., 0.46291005, 0.65465367,
        0.28005602],
       [0.28005602, 1.        , 0.60024505, ..., 0.77784447, 0.5500191 ,
        0.82352941],
       [0.20412415, 0.60024505, 1.        , ..., 0.37796447, 0.6681531 ,
        0.51449576],
       ...,
       [0.46291005, 0.77784447, 0.37796447, ..., 1.        , 0.50507627,
        0.7130241 ],
       [0.65465367, 0.5500191 , 0.6681531 , ..., 0.50507627, 1.        ,
        0.5500191 ],
       [0.28005602, 0.82352941, 0.51449576, ..., 0.7130241 , 0.5500191 ,
        1.        ]])

In [55]:
Similarity_df = pd.DataFrame(user_sim, index = df.index, columns = df.index)
Similarity_df

,0,1,2,3,4,5,6,7,8,9,...,139,140,141,142,143,144,145,146,147,148
0,1.000000,0.280056,0.204124,0.258199,0.000000,0.174078,0.182574,0.447214,0.160128,0.280056,...,0.264906,0.365148,0.348155,0.348155,0.144338,0.000000,0.471405,0.462910,0.654654,0.280056
1,0.280056,1.000000,0.600245,0.921954,0.121268,0.731272,0.536875,0.751469,0.739940,0.882353,...,0.890264,0.613572,0.731272,0.731272,0.727607,0.600245,0.495074,0.777844,0.550019,0.823529
2,0.204124,0.600245,1.000000,0.553399,0.000000,0.746203,0.447214,0.639010,0.490290,0.600245,...,0.648886,0.447214,0.639602,0.426401,0.530330,0.375000,0.433013,0.377964,0.668153,0.514496
3,0.258199,0.921954,0.553399,1.000000,0.111803,0.674200,0.565685,0.750555,0.682191,0.867722,...,0.872082,0.565685,0.674200,0.741620,0.782624,0.632456,0.456435,0.717137,0.507093,0.813489
4,0.000000,0.121268,0.000000,0.111803,1.000000,0.000000,0.158114,0.129099,0.138675,0.121268,...,0.000000,0.000000,0.150756,0.150756,0.125000,0.176777,0.204124,0.133631,0.000000,0.121268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,0.000000,0.600245,0.375000,0.632456,0.176777,0.533002,0.447214,0.547723,0.490290,0.685994,...,0.486664,0.447214,0.533002,0.639602,0.530330,1.000000,0.288675,0.377964,0.400892,0.514496
145,0.471405,0.495074,0.433013,0.456435,0.204124,0.492366,0.645497,0.632456,0.452911,0.495074,...,0.374634,0.516398,0.492366,0.369274,0.510310,0.288675,1.000000,0.654654,0.617213,0.495074
146,0.462910,0.777844,0.377964,0.717137,0.133631,0.483494,0.676123,0.690066,0.741249,0.713024,...,0.674453,0.591608,0.564076,0.564076,0.601338,0.377964,0.654654,1.000000,0.505076,0.713024
147,0.654654,0.550019,0.668153,0.507093,0.000000,0.569803,0.358569,0.585540,0.314485,0.550019,...,0.520266,0.478091,0.569803,0.569803,0.377964,0.400892,0.617213,0.505076,1.000000,0.550019
148,0.280056,0.823529,0.514496,0.813489,0.121268,0.658145,0.536875,0.751469,0.807207,0.764706,...,0.778981,0.690268,0.585018,0.585018,0.788241,0.514496,0.495074,0.713024,0.550019,1.000000

In [57]:
# Function to clean comma-separated fields
def clean_food_list(cell):
    if pd.isna(cell):
        return []
    return [f.strip().lower() for f in cell.split(',')]

#choose target user (e.g. index 1)
target_user = 1

# Top 3 Similar users(excluding self)
similar_users = Similarity_df[target_user].drop(target_user).sort_values(ascending=False)
similar_users

3      0.921954
112    0.921954
58     0.899735
139    0.890264
9      0.882353
         ...
0      0.280056
120    0.242536
134    0.216930
4      0.121268
39     0.121268
Name: 1, Length: 148, dtype: float64

In [59]:
# mean_prefence scores from similar uses
mean_scores =  user_food_matrix.iloc[similar_users].mean()
mean_scores

                                     0.0
egg                                  0.0
fried rice                           0.0
moi-moi                              1.0
indomie and egg                      1.0
starch                               0.0
eba                                  0.0
rice                                 0.0
fufu                                 0.0
semo                                 0.0
bread and omlette with some tea      0.0
alfredo pasta                        0.0
meat                                 0.0
shawarma and chips                   0.0
egusi soup                           0.0
yam                                  0.0
starch and other swallows            0.0
coffee                               0.0
eba and soup                         0.0
cereal                               0.0
fried yam/potatoes and vegetables    0.0
pizza 🍕                              0.0
amala                                0.0
potato                               0.0
i dont eat dinner                    0.0
spaghetti                            0.0
chicken                              0.0
pizza and ice cream (sweet cream     0.0
smoothie                             0.0
fruit salad                          0.0
intercontinental dishes              0.0
fish                                 0.0
white rice                           0.0
beans                                0.0
pounded yam                          0.0
bread                                0.0
anything my money can get me         0.0
youghurt                             0.0
soda drink                           0.0
salad & fruits                       0.0
coochie                              0.0
bread and egg                        0.0
plaintain                            0.0
tea                                  0.0
jollof rice                          1.0
bread and tea.. i guess              0.0
toast bread                          0.0
cerael                               0.0
dtype: float64

In [41]:
# Remove foods the user already likes/dislikes & allergies
liked = set(df.loc[target_user,'preferences'])
disliked = set(clean_food_list(df.loc[target_user,'dislikes']))
allergic = set(clean_food_list(df.loc[target_user,'allergies']))
blocked = liked.union(disliked).union(allergic)

In [61]:
liked

{'amala',
 'beans',
 'bread',
 'chicken',
 'egg',
 'fried rice',
 'indomie and egg',
 'jollof rice',
 'meat',
 'plaintain',
 'pounded yam',
 'semo',
 'smoothie',
 'spaghetti',
 'white rice',
 'yam',
 'youghurt'}

In [63]:
disliked

{'fish', 'soda drink'}

In [65]:
allergic

{'nil'}

In [67]:
blocked

{'amala',
 'beans',
 'bread',
 'chicken',
 'egg',
 'fish',
 'fried rice',
 'indomie and egg',
 'jollof rice',
 'meat',
 'nil',
 'plaintain',
 'pounded yam',
 'semo',
 'smoothie',
 'soda drink',
 'spaghetti',
 'white rice',
 'yam',
 'youghurt'}

In [45]:
# Recommend top 10 new foods
recommendations = mean_scores.drop(labels=blocked,errors='ignore').sort_values(ascending=False).head(10)
print("Top 10 Recommended Foods:\n",recommendations)

Top 10 Recommended Foods:
 moi-moi                         1.0
                                0.0
pizza 🍕                         0.0
toast bread                     0.0
bread and tea.. i guess         0.0
tea                             0.0
bread and egg                   0.0
coochie                         0.0
salad & fruits                  0.0
anything my money can get me    0.0
dtype: float64